#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#--------------------------------------------------------------------

rm -rf constant/poyMesh > /dev/null 2>&1

cleanCase

#--------------------------------------------------------------------
