#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
./Clean

#--------------------------------------------------------------------

# runApplication surfaceFeatureExtract
runApplication blockMesh
# runApplication setFields

runApplication decomposePar

# runApplication $(getApplication)
runParallel $(getApplication)

runApplication reconstructPar

#--------------------------------------------------------------------
