#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
./Clean

#--------------------------------------------------------------------

runApplication blockMesh
runApplication surfaceFeatureExtract

# runApplication decomposePar #-copyZero
# runParallel snappyHexMesh #-overwrite

runApplication snappyHexMesh #-overwrite

# runApplication reconstructParMesh -constant
# runApplication reconstructPar -latestTime

#--------------------------------------------------------------------
